#!/bin/sh
# preinst script for gnupg1-curl
#
# see: dh_installdeb(1)

set -e

if [ "$1" = install ] || [ "$1" = upgrade ] ; then
	dpkg-divert --package gnupg1-curl \
	   --divert /usr/lib/gnupg1/gpgkeys_curl.non_curl \
	   --rename /usr/lib/gnupg1/gpgkeys_curl
	dpkg-divert --package gnupg1-curl \
	   --divert /usr/lib/gnupg1/gpgkeys_hkp.non_curl \
	   --rename /usr/lib/gnupg1/gpgkeys_hkp
fi

#DEBHELPER#

exit 0
